[package]
name = "svgdraw"
version = "0.1.0"
publish = false
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2.97"
web-sys = "0.3.74"
xilem_web = { path = "../.." }
