// Copyright 2025 the Xilem Authors
// SPDX-License-Identifier: Apache-2.0

// Most of this file is copy-pasted directly from
// https://github.com/DioxusLabs/blitz/blob/main/packages/blitz-shell/src/convert_events.rs
// Should be removed once https://github.com/rust-windowing/winit/pull/4026 is merged.

use keyboard_types::{Code, Key, KeyState, KeyboardEvent, Location, Modifiers, NamedKey};
use winit::event::ElementState;
use winit::event::Force as WinitForce;
use winit::event::Ime as WinitIme;
use winit::event::KeyEvent as WinitKeyEvent;
use winit::event::MouseButton as WinitMouseButton;
use winit::keyboard::Key as WinitKey;
use winit::keyboard::KeyCode as WinitKeyCode;
use winit::keyboard::KeyLocation as WinitKeyLocation;
use winit::keyboard::ModifiersState as WinitModifiers;
use winit::keyboard::NamedKey as WinitNamedKey;
use winit::keyboard::PhysicalKey as WinitPhysicalKey;
use winit::window::ResizeDirection as WinitResizeDirection;

use crate::core::{Force, Ime, PointerButton, ResizeDirection};

pub(crate) fn winit_mouse_button_to_masonry(button: WinitMouseButton) -> PointerButton {
    match button {
        WinitMouseButton::Left => PointerButton::Primary,
        WinitMouseButton::Right => PointerButton::Secondary,
        WinitMouseButton::Middle => PointerButton::Auxiliary,
        WinitMouseButton::Back => PointerButton::X1,
        WinitMouseButton::Forward => PointerButton::X2,
        WinitMouseButton::Other(_) => PointerButton::Other,
    }
}
pub(crate) fn masonry_resize_direction_to_winit(dir: ResizeDirection) -> WinitResizeDirection {
    match dir {
        ResizeDirection::East => WinitResizeDirection::East,
        ResizeDirection::North => WinitResizeDirection::North,
        ResizeDirection::NorthEast => WinitResizeDirection::NorthEast,
        ResizeDirection::NorthWest => WinitResizeDirection::NorthWest,
        ResizeDirection::South => WinitResizeDirection::South,
        ResizeDirection::SouthEast => WinitResizeDirection::SouthEast,
        ResizeDirection::SouthWest => WinitResizeDirection::SouthWest,
        ResizeDirection::West => WinitResizeDirection::West,
    }
}

pub(crate) fn winit_force_to_masonry(force: WinitForce) -> Force {
    match force {
        WinitForce::Calibrated {
            force,
            max_possible_force,
            altitude_angle,
        } => Force::Calibrated {
            force,
            max_possible_force,
            altitude_angle,
        },
        WinitForce::Normalized(value) => Force::Normalized(value),
    }
}

pub(crate) fn winit_ime_to_masonry(event: WinitIme) -> Ime {
    match event {
        WinitIme::Enabled => Ime::Enabled,
        WinitIme::Disabled => Ime::Disabled,
        WinitIme::Preedit(text, cursor) => Ime::Preedit(text, cursor),
        WinitIme::Commit(text) => Ime::Commit(text),
    }
}

pub(crate) fn winit_key_event_to_kbt(event: &WinitKeyEvent, mods: WinitModifiers) -> KeyboardEvent {
    KeyboardEvent {
        key: winit_key_to_kbt_key(&event.logical_key),
        code: winit_physical_key_to_kbt_code(event.physical_key),
        modifiers: winit_modifiers_to_kbt_modifiers(mods),
        location: winit_key_location_to_kbt_location(event.location),
        is_composing: false,
        state: match event.state {
            ElementState::Pressed => KeyState::Down,
            ElementState::Released => KeyState::Up,
        },
        repeat: event.repeat,
    }
}

pub(crate) fn winit_modifiers_to_kbt_modifiers(winit_modifiers: WinitModifiers) -> Modifiers {
    let mut modifiers = Modifiers::default();
    if winit_modifiers.control_key() {
        modifiers.insert(Modifiers::CONTROL);
    }
    if winit_modifiers.alt_key() {
        modifiers.insert(Modifiers::ALT);
    }
    if winit_modifiers.shift_key() {
        modifiers.insert(Modifiers::SHIFT);
    }
    if winit_modifiers.super_key() {
        modifiers.insert(Modifiers::META);
    }
    modifiers
}

pub(crate) fn winit_key_location_to_kbt_location(location: WinitKeyLocation) -> Location {
    match location {
        WinitKeyLocation::Standard => Location::Standard,
        WinitKeyLocation::Left => Location::Left,
        WinitKeyLocation::Right => Location::Right,
        WinitKeyLocation::Numpad => Location::Numpad,
    }
}

pub(crate) fn winit_physical_key_to_kbt_code(physical_key: WinitPhysicalKey) -> Code {
    match physical_key {
        WinitPhysicalKey::Unidentified(_) => Code::Unidentified,
        WinitPhysicalKey::Code(key_code) => match key_code {
            // Variants that don't match 1:1
            // With winit 0.31, these are renamed to swap the meta and super to match the W3C specs.
            #[expect(deprecated, reason = "Map even the deprecated keys.")]
            WinitKeyCode::Meta => Code::Super,
            WinitKeyCode::SuperLeft => Code::MetaLeft,
            WinitKeyCode::SuperRight => Code::MetaRight,

            WinitKeyCode::Backquote => Code::Backquote,
            WinitKeyCode::Backslash => Code::Backslash,
            WinitKeyCode::BracketLeft => Code::BracketLeft,
            WinitKeyCode::BracketRight => Code::BracketRight,
            WinitKeyCode::Comma => Code::Comma,
            WinitKeyCode::Digit0 => Code::Digit0,
            WinitKeyCode::Digit1 => Code::Digit1,
            WinitKeyCode::Digit2 => Code::Digit2,
            WinitKeyCode::Digit3 => Code::Digit3,
            WinitKeyCode::Digit4 => Code::Digit4,
            WinitKeyCode::Digit5 => Code::Digit5,
            WinitKeyCode::Digit6 => Code::Digit6,
            WinitKeyCode::Digit7 => Code::Digit7,
            WinitKeyCode::Digit8 => Code::Digit8,
            WinitKeyCode::Digit9 => Code::Digit9,
            WinitKeyCode::Equal => Code::Equal,
            WinitKeyCode::IntlBackslash => Code::IntlBackslash,
            WinitKeyCode::IntlRo => Code::IntlRo,
            WinitKeyCode::IntlYen => Code::IntlYen,
            WinitKeyCode::KeyA => Code::KeyA,
            WinitKeyCode::KeyB => Code::KeyB,
            WinitKeyCode::KeyC => Code::KeyC,
            WinitKeyCode::KeyD => Code::KeyD,
            WinitKeyCode::KeyE => Code::KeyE,
            WinitKeyCode::KeyF => Code::KeyF,
            WinitKeyCode::KeyG => Code::KeyG,
            WinitKeyCode::KeyH => Code::KeyH,
            WinitKeyCode::KeyI => Code::KeyI,
            WinitKeyCode::KeyJ => Code::KeyJ,
            WinitKeyCode::KeyK => Code::KeyK,
            WinitKeyCode::KeyL => Code::KeyL,
            WinitKeyCode::KeyM => Code::KeyM,
            WinitKeyCode::KeyN => Code::KeyN,
            WinitKeyCode::KeyO => Code::KeyO,
            WinitKeyCode::KeyP => Code::KeyP,
            WinitKeyCode::KeyQ => Code::KeyQ,
            WinitKeyCode::KeyR => Code::KeyR,
            WinitKeyCode::KeyS => Code::KeyS,
            WinitKeyCode::KeyT => Code::KeyT,
            WinitKeyCode::KeyU => Code::KeyU,
            WinitKeyCode::KeyV => Code::KeyV,
            WinitKeyCode::KeyW => Code::KeyW,
            WinitKeyCode::KeyX => Code::KeyX,
            WinitKeyCode::KeyY => Code::KeyY,
            WinitKeyCode::KeyZ => Code::KeyZ,
            WinitKeyCode::Minus => Code::Minus,
            WinitKeyCode::Period => Code::Period,
            WinitKeyCode::Quote => Code::Quote,
            WinitKeyCode::Semicolon => Code::Semicolon,
            WinitKeyCode::Slash => Code::Slash,
            WinitKeyCode::AltLeft => Code::AltLeft,
            WinitKeyCode::AltRight => Code::AltRight,
            WinitKeyCode::Backspace => Code::Backspace,
            WinitKeyCode::CapsLock => Code::CapsLock,
            WinitKeyCode::ContextMenu => Code::ContextMenu,
            WinitKeyCode::ControlLeft => Code::ControlLeft,
            WinitKeyCode::ControlRight => Code::ControlRight,
            WinitKeyCode::Enter => Code::Enter,
            WinitKeyCode::ShiftLeft => Code::ShiftLeft,
            WinitKeyCode::ShiftRight => Code::ShiftRight,
            WinitKeyCode::Space => Code::Space,
            WinitKeyCode::Tab => Code::Tab,
            WinitKeyCode::Convert => Code::Convert,
            WinitKeyCode::KanaMode => Code::KanaMode,
            WinitKeyCode::Lang1 => Code::Lang1,
            WinitKeyCode::Lang2 => Code::Lang2,
            WinitKeyCode::Lang3 => Code::Lang3,
            WinitKeyCode::Lang4 => Code::Lang4,
            WinitKeyCode::Lang5 => Code::Lang5,
            WinitKeyCode::NonConvert => Code::NonConvert,
            WinitKeyCode::Delete => Code::Delete,
            WinitKeyCode::End => Code::End,
            WinitKeyCode::Help => Code::Help,
            WinitKeyCode::Home => Code::Home,
            WinitKeyCode::Insert => Code::Insert,
            WinitKeyCode::PageDown => Code::PageDown,
            WinitKeyCode::PageUp => Code::PageUp,
            WinitKeyCode::ArrowDown => Code::ArrowDown,
            WinitKeyCode::ArrowLeft => Code::ArrowLeft,
            WinitKeyCode::ArrowRight => Code::ArrowRight,
            WinitKeyCode::ArrowUp => Code::ArrowUp,
            WinitKeyCode::NumLock => Code::NumLock,
            WinitKeyCode::Numpad0 => Code::Numpad0,
            WinitKeyCode::Numpad1 => Code::Numpad1,
            WinitKeyCode::Numpad2 => Code::Numpad2,
            WinitKeyCode::Numpad3 => Code::Numpad3,
            WinitKeyCode::Numpad4 => Code::Numpad4,
            WinitKeyCode::Numpad5 => Code::Numpad5,
            WinitKeyCode::Numpad6 => Code::Numpad6,
            WinitKeyCode::Numpad7 => Code::Numpad7,
            WinitKeyCode::Numpad8 => Code::Numpad8,
            WinitKeyCode::Numpad9 => Code::Numpad9,
            WinitKeyCode::NumpadAdd => Code::NumpadAdd,
            WinitKeyCode::NumpadBackspace => Code::NumpadBackspace,
            WinitKeyCode::NumpadClear => Code::NumpadClear,
            WinitKeyCode::NumpadClearEntry => Code::NumpadClearEntry,
            WinitKeyCode::NumpadComma => Code::NumpadComma,
            WinitKeyCode::NumpadDecimal => Code::NumpadDecimal,
            WinitKeyCode::NumpadDivide => Code::NumpadDivide,
            WinitKeyCode::NumpadEnter => Code::NumpadEnter,
            WinitKeyCode::NumpadEqual => Code::NumpadEqual,
            WinitKeyCode::NumpadHash => Code::NumpadHash,
            WinitKeyCode::NumpadMemoryAdd => Code::NumpadMemoryAdd,
            WinitKeyCode::NumpadMemoryClear => Code::NumpadMemoryClear,
            WinitKeyCode::NumpadMemoryRecall => Code::NumpadMemoryRecall,
            WinitKeyCode::NumpadMemoryStore => Code::NumpadMemoryStore,
            WinitKeyCode::NumpadMemorySubtract => Code::NumpadMemorySubtract,
            WinitKeyCode::NumpadMultiply => Code::NumpadMultiply,
            WinitKeyCode::NumpadParenLeft => Code::NumpadParenLeft,
            WinitKeyCode::NumpadParenRight => Code::NumpadParenRight,
            WinitKeyCode::NumpadStar => Code::NumpadStar,
            WinitKeyCode::NumpadSubtract => Code::NumpadSubtract,
            WinitKeyCode::Escape => Code::Escape,
            WinitKeyCode::Fn => Code::Fn,
            WinitKeyCode::FnLock => Code::FnLock,
            WinitKeyCode::PrintScreen => Code::PrintScreen,
            WinitKeyCode::ScrollLock => Code::ScrollLock,
            WinitKeyCode::Pause => Code::Pause,
            WinitKeyCode::BrowserBack => Code::BrowserBack,
            WinitKeyCode::BrowserFavorites => Code::BrowserFavorites,
            WinitKeyCode::BrowserForward => Code::BrowserForward,
            WinitKeyCode::BrowserHome => Code::BrowserHome,
            WinitKeyCode::BrowserRefresh => Code::BrowserRefresh,
            WinitKeyCode::BrowserSearch => Code::BrowserSearch,
            WinitKeyCode::BrowserStop => Code::BrowserStop,
            WinitKeyCode::Eject => Code::Eject,
            WinitKeyCode::LaunchApp1 => Code::LaunchApp1,
            WinitKeyCode::LaunchApp2 => Code::LaunchApp2,
            WinitKeyCode::LaunchMail => Code::LaunchMail,
            WinitKeyCode::MediaPlayPause => Code::MediaPlayPause,
            WinitKeyCode::MediaSelect => Code::MediaSelect,
            WinitKeyCode::MediaStop => Code::MediaStop,
            WinitKeyCode::MediaTrackNext => Code::MediaTrackNext,
            WinitKeyCode::MediaTrackPrevious => Code::MediaTrackPrevious,
            WinitKeyCode::Power => Code::Power,
            WinitKeyCode::Sleep => Code::Sleep,
            WinitKeyCode::AudioVolumeDown => Code::AudioVolumeDown,
            WinitKeyCode::AudioVolumeMute => Code::AudioVolumeMute,
            WinitKeyCode::AudioVolumeUp => Code::AudioVolumeUp,
            WinitKeyCode::WakeUp => Code::WakeUp,
            #[expect(deprecated, reason = "Map even the deprecated keys.")]
            WinitKeyCode::Hyper => Code::Hyper,
            #[expect(deprecated, reason = "Map even the deprecated keys.")]
            WinitKeyCode::Turbo => Code::Turbo,
            WinitKeyCode::Abort => Code::Abort,
            WinitKeyCode::Resume => Code::Resume,
            WinitKeyCode::Suspend => Code::Suspend,
            WinitKeyCode::Again => Code::Again,
            WinitKeyCode::Copy => Code::Copy,
            WinitKeyCode::Cut => Code::Cut,
            WinitKeyCode::Find => Code::Find,
            WinitKeyCode::Open => Code::Open,
            WinitKeyCode::Paste => Code::Paste,
            WinitKeyCode::Props => Code::Props,
            WinitKeyCode::Select => Code::Select,
            WinitKeyCode::Undo => Code::Undo,
            WinitKeyCode::Hiragana => Code::Hiragana,
            WinitKeyCode::Katakana => Code::Katakana,
            WinitKeyCode::F1 => Code::F1,
            WinitKeyCode::F2 => Code::F2,
            WinitKeyCode::F3 => Code::F3,
            WinitKeyCode::F4 => Code::F4,
            WinitKeyCode::F5 => Code::F5,
            WinitKeyCode::F6 => Code::F6,
            WinitKeyCode::F7 => Code::F7,
            WinitKeyCode::F8 => Code::F8,
            WinitKeyCode::F9 => Code::F9,
            WinitKeyCode::F10 => Code::F10,
            WinitKeyCode::F11 => Code::F11,
            WinitKeyCode::F12 => Code::F12,
            WinitKeyCode::F13 => Code::F13,
            WinitKeyCode::F14 => Code::F14,
            WinitKeyCode::F15 => Code::F15,
            WinitKeyCode::F16 => Code::F16,
            WinitKeyCode::F17 => Code::F17,
            WinitKeyCode::F18 => Code::F18,
            WinitKeyCode::F19 => Code::F19,
            WinitKeyCode::F20 => Code::F20,
            WinitKeyCode::F21 => Code::F21,
            WinitKeyCode::F22 => Code::F22,
            WinitKeyCode::F23 => Code::F23,
            WinitKeyCode::F24 => Code::F24,
            WinitKeyCode::F25 => Code::F25,
            WinitKeyCode::F26 => Code::F26,
            WinitKeyCode::F27 => Code::F27,
            WinitKeyCode::F28 => Code::F28,
            WinitKeyCode::F29 => Code::F29,
            WinitKeyCode::F30 => Code::F30,
            WinitKeyCode::F31 => Code::F31,
            WinitKeyCode::F32 => Code::F32,
            WinitKeyCode::F33 => Code::F33,
            WinitKeyCode::F34 => Code::F34,
            WinitKeyCode::F35 => Code::F35,
            _ => Code::Unidentified,
        },
    }
}

pub(crate) fn winit_key_to_kbt_key(winit_key: &WinitKey) -> Key {
    match winit_key {
        WinitKey::Character(c) => Key::Character(c.to_string()),
        WinitKey::Unidentified(_) => Key::Named(NamedKey::Unidentified),
        WinitKey::Dead(_) => Key::Named(NamedKey::Dead),
        WinitKey::Named(named_key) => match named_key {
            WinitNamedKey::Alt => Key::Named(NamedKey::Alt),
            WinitNamedKey::AltGraph => Key::Named(NamedKey::AltGraph),
            WinitNamedKey::CapsLock => Key::Named(NamedKey::CapsLock),
            WinitNamedKey::Control => Key::Named(NamedKey::Control),
            WinitNamedKey::Fn => Key::Named(NamedKey::Fn),
            WinitNamedKey::FnLock => Key::Named(NamedKey::FnLock),
            WinitNamedKey::NumLock => Key::Named(NamedKey::NumLock),
            WinitNamedKey::ScrollLock => Key::Named(NamedKey::ScrollLock),
            WinitNamedKey::Shift => Key::Named(NamedKey::Shift),
            WinitNamedKey::Symbol => Key::Named(NamedKey::Symbol),
            WinitNamedKey::SymbolLock => Key::Named(NamedKey::SymbolLock),
            #[expect(deprecated, reason = "Map even the deprecated keys.")]
            WinitNamedKey::Meta => Key::Named(NamedKey::Super),
            #[expect(deprecated, reason = "Map even the deprecated keys.")]
            WinitNamedKey::Hyper => Key::Named(NamedKey::Hyper),
            WinitNamedKey::Super => Key::Named(NamedKey::Meta),
            WinitNamedKey::Enter => Key::Named(NamedKey::Enter),
            WinitNamedKey::Tab => Key::Named(NamedKey::Tab),
            WinitNamedKey::Space => Key::Character(" ".to_string()),
            WinitNamedKey::ArrowDown => Key::Named(NamedKey::ArrowDown),
            WinitNamedKey::ArrowLeft => Key::Named(NamedKey::ArrowLeft),
            WinitNamedKey::ArrowRight => Key::Named(NamedKey::ArrowRight),
            WinitNamedKey::ArrowUp => Key::Named(NamedKey::ArrowUp),
            WinitNamedKey::End => Key::Named(NamedKey::End),
            WinitNamedKey::Home => Key::Named(NamedKey::Home),
            WinitNamedKey::PageDown => Key::Named(NamedKey::PageDown),
            WinitNamedKey::PageUp => Key::Named(NamedKey::PageUp),
            WinitNamedKey::Backspace => Key::Named(NamedKey::Backspace),
            WinitNamedKey::Clear => Key::Named(NamedKey::Clear),
            WinitNamedKey::Copy => Key::Named(NamedKey::Copy),
            WinitNamedKey::CrSel => Key::Named(NamedKey::CrSel),
            WinitNamedKey::Cut => Key::Named(NamedKey::Cut),
            WinitNamedKey::Delete => Key::Named(NamedKey::Delete),
            WinitNamedKey::EraseEof => Key::Named(NamedKey::EraseEof),
            WinitNamedKey::ExSel => Key::Named(NamedKey::ExSel),
            WinitNamedKey::Insert => Key::Named(NamedKey::Insert),
            WinitNamedKey::Paste => Key::Named(NamedKey::Paste),
            WinitNamedKey::Redo => Key::Named(NamedKey::Redo),
            WinitNamedKey::Undo => Key::Named(NamedKey::Undo),
            WinitNamedKey::Accept => Key::Named(NamedKey::Accept),
            WinitNamedKey::Again => Key::Named(NamedKey::Again),
            WinitNamedKey::Attn => Key::Named(NamedKey::Attn),
            WinitNamedKey::Cancel => Key::Named(NamedKey::Cancel),
            WinitNamedKey::ContextMenu => Key::Named(NamedKey::ContextMenu),
            WinitNamedKey::Escape => Key::Named(NamedKey::Escape),
            WinitNamedKey::Execute => Key::Named(NamedKey::Execute),
            WinitNamedKey::Find => Key::Named(NamedKey::Find),
            WinitNamedKey::Help => Key::Named(NamedKey::Help),
            WinitNamedKey::Pause => Key::Named(NamedKey::Pause),
            WinitNamedKey::Play => Key::Named(NamedKey::Play),
            WinitNamedKey::Props => Key::Named(NamedKey::Props),
            WinitNamedKey::Select => Key::Named(NamedKey::Select),
            WinitNamedKey::ZoomIn => Key::Named(NamedKey::ZoomIn),
            WinitNamedKey::ZoomOut => Key::Named(NamedKey::ZoomOut),
            WinitNamedKey::BrightnessDown => Key::Named(NamedKey::BrightnessDown),
            WinitNamedKey::BrightnessUp => Key::Named(NamedKey::BrightnessUp),
            WinitNamedKey::Eject => Key::Named(NamedKey::Eject),
            WinitNamedKey::LogOff => Key::Named(NamedKey::LogOff),
            WinitNamedKey::Power => Key::Named(NamedKey::Power),
            WinitNamedKey::PowerOff => Key::Named(NamedKey::PowerOff),
            WinitNamedKey::PrintScreen => Key::Named(NamedKey::PrintScreen),
            WinitNamedKey::Hibernate => Key::Named(NamedKey::Hibernate),
            WinitNamedKey::Standby => Key::Named(NamedKey::Standby),
            WinitNamedKey::WakeUp => Key::Named(NamedKey::WakeUp),
            WinitNamedKey::AllCandidates => Key::Named(NamedKey::AllCandidates),
            WinitNamedKey::Alphanumeric => Key::Named(NamedKey::Alphanumeric),
            WinitNamedKey::CodeInput => Key::Named(NamedKey::CodeInput),
            WinitNamedKey::Compose => Key::Named(NamedKey::Compose),
            WinitNamedKey::Convert => Key::Named(NamedKey::Convert),
            WinitNamedKey::FinalMode => Key::Named(NamedKey::FinalMode),
            WinitNamedKey::GroupFirst => Key::Named(NamedKey::GroupFirst),
            WinitNamedKey::GroupLast => Key::Named(NamedKey::GroupLast),
            WinitNamedKey::GroupNext => Key::Named(NamedKey::GroupNext),
            WinitNamedKey::GroupPrevious => Key::Named(NamedKey::GroupPrevious),
            WinitNamedKey::ModeChange => Key::Named(NamedKey::ModeChange),
            WinitNamedKey::NextCandidate => Key::Named(NamedKey::NextCandidate),
            WinitNamedKey::NonConvert => Key::Named(NamedKey::NonConvert),
            WinitNamedKey::PreviousCandidate => Key::Named(NamedKey::PreviousCandidate),
            WinitNamedKey::Process => Key::Named(NamedKey::Process),
            WinitNamedKey::SingleCandidate => Key::Named(NamedKey::SingleCandidate),
            WinitNamedKey::HangulMode => Key::Named(NamedKey::HangulMode),
            WinitNamedKey::HanjaMode => Key::Named(NamedKey::HanjaMode),
            WinitNamedKey::JunjaMode => Key::Named(NamedKey::JunjaMode),
            WinitNamedKey::Eisu => Key::Named(NamedKey::Eisu),
            WinitNamedKey::Hankaku => Key::Named(NamedKey::Hankaku),
            WinitNamedKey::Hiragana => Key::Named(NamedKey::Hiragana),
            WinitNamedKey::HiraganaKatakana => Key::Named(NamedKey::HiraganaKatakana),
            WinitNamedKey::KanaMode => Key::Named(NamedKey::KanaMode),
            WinitNamedKey::KanjiMode => Key::Named(NamedKey::KanjiMode),
            WinitNamedKey::Katakana => Key::Named(NamedKey::Katakana),
            WinitNamedKey::Romaji => Key::Named(NamedKey::Romaji),
            WinitNamedKey::Zenkaku => Key::Named(NamedKey::Zenkaku),
            WinitNamedKey::ZenkakuHankaku => Key::Named(NamedKey::ZenkakuHankaku),
            WinitNamedKey::Soft1 => Key::Named(NamedKey::Soft1),
            WinitNamedKey::Soft2 => Key::Named(NamedKey::Soft2),
            WinitNamedKey::Soft3 => Key::Named(NamedKey::Soft3),
            WinitNamedKey::Soft4 => Key::Named(NamedKey::Soft4),
            WinitNamedKey::ChannelDown => Key::Named(NamedKey::ChannelDown),
            WinitNamedKey::ChannelUp => Key::Named(NamedKey::ChannelUp),
            WinitNamedKey::Close => Key::Named(NamedKey::Close),
            WinitNamedKey::MailForward => Key::Named(NamedKey::MailForward),
            WinitNamedKey::MailReply => Key::Named(NamedKey::MailReply),
            WinitNamedKey::MailSend => Key::Named(NamedKey::MailSend),
            WinitNamedKey::MediaClose => Key::Named(NamedKey::MediaClose),
            WinitNamedKey::MediaFastForward => Key::Named(NamedKey::MediaFastForward),
            WinitNamedKey::MediaPause => Key::Named(NamedKey::MediaPause),
            WinitNamedKey::MediaPlay => Key::Named(NamedKey::MediaPlay),
            WinitNamedKey::MediaPlayPause => Key::Named(NamedKey::MediaPlayPause),
            WinitNamedKey::MediaRecord => Key::Named(NamedKey::MediaRecord),
            WinitNamedKey::MediaRewind => Key::Named(NamedKey::MediaRewind),
            WinitNamedKey::MediaStop => Key::Named(NamedKey::MediaStop),
            WinitNamedKey::MediaTrackNext => Key::Named(NamedKey::MediaTrackNext),
            WinitNamedKey::MediaTrackPrevious => Key::Named(NamedKey::MediaTrackPrevious),
            WinitNamedKey::New => Key::Named(NamedKey::New),
            WinitNamedKey::Open => Key::Named(NamedKey::Open),
            WinitNamedKey::Print => Key::Named(NamedKey::Print),
            WinitNamedKey::Save => Key::Named(NamedKey::Save),
            WinitNamedKey::SpellCheck => Key::Named(NamedKey::SpellCheck),
            WinitNamedKey::Key11 => Key::Named(NamedKey::Key11),
            WinitNamedKey::Key12 => Key::Named(NamedKey::Key12),
            WinitNamedKey::AudioBalanceLeft => Key::Named(NamedKey::AudioBalanceLeft),
            WinitNamedKey::AudioBalanceRight => Key::Named(NamedKey::AudioBalanceRight),
            WinitNamedKey::AudioBassBoostDown => Key::Named(NamedKey::AudioBassBoostDown),
            WinitNamedKey::AudioBassBoostToggle => Key::Named(NamedKey::AudioBassBoostToggle),
            WinitNamedKey::AudioBassBoostUp => Key::Named(NamedKey::AudioBassBoostUp),
            WinitNamedKey::AudioFaderFront => Key::Named(NamedKey::AudioFaderFront),
            WinitNamedKey::AudioFaderRear => Key::Named(NamedKey::AudioFaderRear),
            WinitNamedKey::AudioSurroundModeNext => Key::Named(NamedKey::AudioSurroundModeNext),
            WinitNamedKey::AudioTrebleDown => Key::Named(NamedKey::AudioTrebleDown),
            WinitNamedKey::AudioTrebleUp => Key::Named(NamedKey::AudioTrebleUp),
            WinitNamedKey::AudioVolumeDown => Key::Named(NamedKey::AudioVolumeDown),
            WinitNamedKey::AudioVolumeUp => Key::Named(NamedKey::AudioVolumeUp),
            WinitNamedKey::AudioVolumeMute => Key::Named(NamedKey::AudioVolumeMute),
            WinitNamedKey::MicrophoneToggle => Key::Named(NamedKey::MicrophoneToggle),
            WinitNamedKey::MicrophoneVolumeDown => Key::Named(NamedKey::MicrophoneVolumeDown),
            WinitNamedKey::MicrophoneVolumeUp => Key::Named(NamedKey::MicrophoneVolumeUp),
            WinitNamedKey::MicrophoneVolumeMute => Key::Named(NamedKey::MicrophoneVolumeMute),
            WinitNamedKey::SpeechCorrectionList => Key::Named(NamedKey::SpeechCorrectionList),
            WinitNamedKey::SpeechInputToggle => Key::Named(NamedKey::SpeechInputToggle),
            WinitNamedKey::LaunchApplication1 => Key::Named(NamedKey::LaunchApplication1),
            WinitNamedKey::LaunchApplication2 => Key::Named(NamedKey::LaunchApplication2),
            WinitNamedKey::LaunchCalendar => Key::Named(NamedKey::LaunchCalendar),
            WinitNamedKey::LaunchContacts => Key::Named(NamedKey::LaunchContacts),
            WinitNamedKey::LaunchMail => Key::Named(NamedKey::LaunchMail),
            WinitNamedKey::LaunchMediaPlayer => Key::Named(NamedKey::LaunchMediaPlayer),
            WinitNamedKey::LaunchMusicPlayer => Key::Named(NamedKey::LaunchMusicPlayer),
            WinitNamedKey::LaunchPhone => Key::Named(NamedKey::LaunchPhone),
            WinitNamedKey::LaunchScreenSaver => Key::Named(NamedKey::LaunchScreenSaver),
            WinitNamedKey::LaunchSpreadsheet => Key::Named(NamedKey::LaunchSpreadsheet),
            WinitNamedKey::LaunchWebBrowser => Key::Named(NamedKey::LaunchWebBrowser),
            WinitNamedKey::LaunchWebCam => Key::Named(NamedKey::LaunchWebCam),
            WinitNamedKey::LaunchWordProcessor => Key::Named(NamedKey::LaunchWordProcessor),
            WinitNamedKey::BrowserBack => Key::Named(NamedKey::BrowserBack),
            WinitNamedKey::BrowserFavorites => Key::Named(NamedKey::BrowserFavorites),
            WinitNamedKey::BrowserForward => Key::Named(NamedKey::BrowserForward),
            WinitNamedKey::BrowserHome => Key::Named(NamedKey::BrowserHome),
            WinitNamedKey::BrowserRefresh => Key::Named(NamedKey::BrowserRefresh),
            WinitNamedKey::BrowserSearch => Key::Named(NamedKey::BrowserSearch),
            WinitNamedKey::BrowserStop => Key::Named(NamedKey::BrowserStop),
            WinitNamedKey::AppSwitch => Key::Named(NamedKey::AppSwitch),
            WinitNamedKey::Call => Key::Named(NamedKey::Call),
            WinitNamedKey::Camera => Key::Named(NamedKey::Camera),
            WinitNamedKey::CameraFocus => Key::Named(NamedKey::CameraFocus),
            WinitNamedKey::EndCall => Key::Named(NamedKey::EndCall),
            WinitNamedKey::GoBack => Key::Named(NamedKey::GoBack),
            WinitNamedKey::GoHome => Key::Named(NamedKey::GoHome),
            WinitNamedKey::HeadsetHook => Key::Named(NamedKey::HeadsetHook),
            WinitNamedKey::LastNumberRedial => Key::Named(NamedKey::LastNumberRedial),
            WinitNamedKey::Notification => Key::Named(NamedKey::Notification),
            WinitNamedKey::MannerMode => Key::Named(NamedKey::MannerMode),
            WinitNamedKey::VoiceDial => Key::Named(NamedKey::VoiceDial),
            WinitNamedKey::TV => Key::Named(NamedKey::TV),
            WinitNamedKey::TV3DMode => Key::Named(NamedKey::TV3DMode),
            WinitNamedKey::TVAntennaCable => Key::Named(NamedKey::TVAntennaCable),
            WinitNamedKey::TVAudioDescription => Key::Named(NamedKey::TVAudioDescription),
            WinitNamedKey::TVAudioDescriptionMixDown => {
                Key::Named(NamedKey::TVAudioDescriptionMixDown)
            }
            WinitNamedKey::TVAudioDescriptionMixUp => Key::Named(NamedKey::TVAudioDescriptionMixUp),
            WinitNamedKey::TVContentsMenu => Key::Named(NamedKey::TVContentsMenu),
            WinitNamedKey::TVDataService => Key::Named(NamedKey::TVDataService),
            WinitNamedKey::TVInput => Key::Named(NamedKey::TVInput),
            WinitNamedKey::TVInputComponent1 => Key::Named(NamedKey::TVInputComponent1),
            WinitNamedKey::TVInputComponent2 => Key::Named(NamedKey::TVInputComponent2),
            WinitNamedKey::TVInputComposite1 => Key::Named(NamedKey::TVInputComposite1),
            WinitNamedKey::TVInputComposite2 => Key::Named(NamedKey::TVInputComposite2),
            WinitNamedKey::TVInputHDMI1 => Key::Named(NamedKey::TVInputHDMI1),
            WinitNamedKey::TVInputHDMI2 => Key::Named(NamedKey::TVInputHDMI2),
            WinitNamedKey::TVInputHDMI3 => Key::Named(NamedKey::TVInputHDMI3),
            WinitNamedKey::TVInputHDMI4 => Key::Named(NamedKey::TVInputHDMI4),
            WinitNamedKey::TVInputVGA1 => Key::Named(NamedKey::TVInputVGA1),
            WinitNamedKey::TVMediaContext => Key::Named(NamedKey::TVMediaContext),
            WinitNamedKey::TVNetwork => Key::Named(NamedKey::TVNetwork),
            WinitNamedKey::TVNumberEntry => Key::Named(NamedKey::TVNumberEntry),
            WinitNamedKey::TVPower => Key::Named(NamedKey::TVPower),
            WinitNamedKey::TVRadioService => Key::Named(NamedKey::TVRadioService),
            WinitNamedKey::TVSatellite => Key::Named(NamedKey::TVSatellite),
            WinitNamedKey::TVSatelliteBS => Key::Named(NamedKey::TVSatelliteBS),
            WinitNamedKey::TVSatelliteCS => Key::Named(NamedKey::TVSatelliteCS),
            WinitNamedKey::TVSatelliteToggle => Key::Named(NamedKey::TVSatelliteToggle),
            WinitNamedKey::TVTerrestrialAnalog => Key::Named(NamedKey::TVTerrestrialAnalog),
            WinitNamedKey::TVTerrestrialDigital => Key::Named(NamedKey::TVTerrestrialDigital),
            WinitNamedKey::TVTimer => Key::Named(NamedKey::TVTimer),
            WinitNamedKey::AVRInput => Key::Named(NamedKey::AVRInput),
            WinitNamedKey::AVRPower => Key::Named(NamedKey::AVRPower),
            WinitNamedKey::ColorF0Red => Key::Named(NamedKey::ColorF0Red),
            WinitNamedKey::ColorF1Green => Key::Named(NamedKey::ColorF1Green),
            WinitNamedKey::ColorF2Yellow => Key::Named(NamedKey::ColorF2Yellow),
            WinitNamedKey::ColorF3Blue => Key::Named(NamedKey::ColorF3Blue),
            WinitNamedKey::ColorF4Grey => Key::Named(NamedKey::ColorF4Grey),
            WinitNamedKey::ColorF5Brown => Key::Named(NamedKey::ColorF5Brown),
            WinitNamedKey::ClosedCaptionToggle => Key::Named(NamedKey::ClosedCaptionToggle),
            WinitNamedKey::Dimmer => Key::Named(NamedKey::Dimmer),
            WinitNamedKey::DisplaySwap => Key::Named(NamedKey::DisplaySwap),
            WinitNamedKey::DVR => Key::Named(NamedKey::DVR),
            WinitNamedKey::Exit => Key::Named(NamedKey::Exit),
            WinitNamedKey::FavoriteClear0 => Key::Named(NamedKey::FavoriteClear0),
            WinitNamedKey::FavoriteClear1 => Key::Named(NamedKey::FavoriteClear1),
            WinitNamedKey::FavoriteClear2 => Key::Named(NamedKey::FavoriteClear2),
            WinitNamedKey::FavoriteClear3 => Key::Named(NamedKey::FavoriteClear3),
            WinitNamedKey::FavoriteRecall0 => Key::Named(NamedKey::FavoriteRecall0),
            WinitNamedKey::FavoriteRecall1 => Key::Named(NamedKey::FavoriteRecall1),
            WinitNamedKey::FavoriteRecall2 => Key::Named(NamedKey::FavoriteRecall2),
            WinitNamedKey::FavoriteRecall3 => Key::Named(NamedKey::FavoriteRecall3),
            WinitNamedKey::FavoriteStore0 => Key::Named(NamedKey::FavoriteStore0),
            WinitNamedKey::FavoriteStore1 => Key::Named(NamedKey::FavoriteStore1),
            WinitNamedKey::FavoriteStore2 => Key::Named(NamedKey::FavoriteStore2),
            WinitNamedKey::FavoriteStore3 => Key::Named(NamedKey::FavoriteStore3),
            WinitNamedKey::Guide => Key::Named(NamedKey::Guide),
            WinitNamedKey::GuideNextDay => Key::Named(NamedKey::GuideNextDay),
            WinitNamedKey::GuidePreviousDay => Key::Named(NamedKey::GuidePreviousDay),
            WinitNamedKey::Info => Key::Named(NamedKey::Info),
            WinitNamedKey::InstantReplay => Key::Named(NamedKey::InstantReplay),
            WinitNamedKey::Link => Key::Named(NamedKey::Link),
            WinitNamedKey::ListProgram => Key::Named(NamedKey::ListProgram),
            WinitNamedKey::LiveContent => Key::Named(NamedKey::LiveContent),
            WinitNamedKey::Lock => Key::Named(NamedKey::Lock),
            WinitNamedKey::MediaApps => Key::Named(NamedKey::MediaApps),
            WinitNamedKey::MediaAudioTrack => Key::Named(NamedKey::MediaAudioTrack),
            WinitNamedKey::MediaLast => Key::Named(NamedKey::MediaLast),
            WinitNamedKey::MediaSkipBackward => Key::Named(NamedKey::MediaSkipBackward),
            WinitNamedKey::MediaSkipForward => Key::Named(NamedKey::MediaSkipForward),
            WinitNamedKey::MediaStepBackward => Key::Named(NamedKey::MediaStepBackward),
            WinitNamedKey::MediaStepForward => Key::Named(NamedKey::MediaStepForward),
            WinitNamedKey::MediaTopMenu => Key::Named(NamedKey::MediaTopMenu),
            WinitNamedKey::NavigateIn => Key::Named(NamedKey::NavigateIn),
            WinitNamedKey::NavigateNext => Key::Named(NamedKey::NavigateNext),
            WinitNamedKey::NavigateOut => Key::Named(NamedKey::NavigateOut),
            WinitNamedKey::NavigatePrevious => Key::Named(NamedKey::NavigatePrevious),
            WinitNamedKey::NextFavoriteChannel => Key::Named(NamedKey::NextFavoriteChannel),
            WinitNamedKey::NextUserProfile => Key::Named(NamedKey::NextUserProfile),
            WinitNamedKey::OnDemand => Key::Named(NamedKey::OnDemand),
            WinitNamedKey::Pairing => Key::Named(NamedKey::Pairing),
            WinitNamedKey::PinPDown => Key::Named(NamedKey::PinPDown),
            WinitNamedKey::PinPMove => Key::Named(NamedKey::PinPMove),
            WinitNamedKey::PinPToggle => Key::Named(NamedKey::PinPToggle),
            WinitNamedKey::PinPUp => Key::Named(NamedKey::PinPUp),
            WinitNamedKey::PlaySpeedDown => Key::Named(NamedKey::PlaySpeedDown),
            WinitNamedKey::PlaySpeedReset => Key::Named(NamedKey::PlaySpeedReset),
            WinitNamedKey::PlaySpeedUp => Key::Named(NamedKey::PlaySpeedUp),
            WinitNamedKey::RandomToggle => Key::Named(NamedKey::RandomToggle),
            WinitNamedKey::RcLowBattery => Key::Named(NamedKey::RcLowBattery),
            WinitNamedKey::RecordSpeedNext => Key::Named(NamedKey::RecordSpeedNext),
            WinitNamedKey::RfBypass => Key::Named(NamedKey::RfBypass),
            WinitNamedKey::ScanChannelsToggle => Key::Named(NamedKey::ScanChannelsToggle),
            WinitNamedKey::ScreenModeNext => Key::Named(NamedKey::ScreenModeNext),
            WinitNamedKey::Settings => Key::Named(NamedKey::Settings),
            WinitNamedKey::SplitScreenToggle => Key::Named(NamedKey::SplitScreenToggle),
            WinitNamedKey::STBInput => Key::Named(NamedKey::STBInput),
            WinitNamedKey::STBPower => Key::Named(NamedKey::STBPower),
            WinitNamedKey::Subtitle => Key::Named(NamedKey::Subtitle),
            WinitNamedKey::Teletext => Key::Named(NamedKey::Teletext),
            WinitNamedKey::VideoModeNext => Key::Named(NamedKey::VideoModeNext),
            WinitNamedKey::Wink => Key::Named(NamedKey::Wink),
            WinitNamedKey::ZoomToggle => Key::Named(NamedKey::ZoomToggle),
            WinitNamedKey::F1 => Key::Named(NamedKey::F1),
            WinitNamedKey::F2 => Key::Named(NamedKey::F2),
            WinitNamedKey::F3 => Key::Named(NamedKey::F3),
            WinitNamedKey::F4 => Key::Named(NamedKey::F4),
            WinitNamedKey::F5 => Key::Named(NamedKey::F5),
            WinitNamedKey::F6 => Key::Named(NamedKey::F6),
            WinitNamedKey::F7 => Key::Named(NamedKey::F7),
            WinitNamedKey::F8 => Key::Named(NamedKey::F8),
            WinitNamedKey::F9 => Key::Named(NamedKey::F9),
            WinitNamedKey::F10 => Key::Named(NamedKey::F10),
            WinitNamedKey::F11 => Key::Named(NamedKey::F11),
            WinitNamedKey::F12 => Key::Named(NamedKey::F12),
            WinitNamedKey::F13 => Key::Named(NamedKey::F13),
            WinitNamedKey::F14 => Key::Named(NamedKey::F14),
            WinitNamedKey::F15 => Key::Named(NamedKey::F15),
            WinitNamedKey::F16 => Key::Named(NamedKey::F16),
            WinitNamedKey::F17 => Key::Named(NamedKey::F17),
            WinitNamedKey::F18 => Key::Named(NamedKey::F18),
            WinitNamedKey::F19 => Key::Named(NamedKey::F19),
            WinitNamedKey::F20 => Key::Named(NamedKey::F20),
            WinitNamedKey::F21 => Key::Named(NamedKey::F21),
            WinitNamedKey::F22 => Key::Named(NamedKey::F22),
            WinitNamedKey::F23 => Key::Named(NamedKey::F23),
            WinitNamedKey::F24 => Key::Named(NamedKey::F24),
            WinitNamedKey::F25 => Key::Named(NamedKey::F25),
            WinitNamedKey::F26 => Key::Named(NamedKey::F26),
            WinitNamedKey::F27 => Key::Named(NamedKey::F27),
            WinitNamedKey::F28 => Key::Named(NamedKey::F28),
            WinitNamedKey::F29 => Key::Named(NamedKey::F29),
            WinitNamedKey::F30 => Key::Named(NamedKey::F30),
            WinitNamedKey::F31 => Key::Named(NamedKey::F31),
            WinitNamedKey::F32 => Key::Named(NamedKey::F32),
            WinitNamedKey::F33 => Key::Named(NamedKey::F33),
            WinitNamedKey::F34 => Key::Named(NamedKey::F34),
            WinitNamedKey::F35 => Key::Named(NamedKey::F35),
            _ => Key::Named(NamedKey::Unidentified),
        },
    }
}
