// Copyright 2019 the Xilem Authors and the Druid Authors
// SPDX-License-Identifier: Apache-2.0

//! Events.

use kurbo::Rect;
use ui_events::keyboard::{Code, Key, KeyState, KeyboardEvent};
use ui_events::text::{CompositionState, TextInputEvent, TextRange};

use crate::dpi::PhysicalSize;
use crate::util::Duration;

// --- MARK: TYPES

/// A global event.
#[derive(Debug, Clone, PartialEq)]
pub enum WindowEvent {
    /// The window's DPI factor changed.
    Rescale(f64),
    /// The window was resized.
    Resize(PhysicalSize<u32>),
    /// The animation frame requested by this window must run.
    AnimFrame(Duration),
    /// The accessibility tree must be updated when rendering the app.
    EnableAccessTree,
    /// The accessibility tree is no longer updated when rendering the app.
    DisableAccessTree,
}

/// A text-related event.
#[derive(Debug, Clone, PartialEq)]
pub enum TextEvent {
    /// A keyboard event.
    Keyboard(KeyboardEvent),
    /// A transport-agnostic text-input event.
    TextInput(TextInputEvent),
    /// The window took or lost focus.
    WindowFocusChange(bool),
    // TODO - Handle rich text copy-pasting
    /// The user pasted content in.
    ClipboardPaste(String),
}

/// An accessibility event.
///
/// This is generated by `accesskit` back-ends when the user interacts with
/// the app using their platform's accessibility APIs.
///
/// For instance, these events are often used by visually impaired users to navigate
/// your app without a mouse.
#[derive(Debug, Clone, PartialEq)]
pub struct AccessEvent {
    /// The action that was performed.
    pub action: accesskit::Action,
    /// Additional data associated with the action.
    pub data: Option<accesskit::ActionData>,
}

/// The light/dark mode of the window.
#[derive(Debug, Clone, PartialEq)]
pub enum WindowTheme {
    /// Light mode.
    Light,
    /// Dark mode.
    Dark,
}

/// Changes to widget state.
///
/// Unlike [`PointerEvent`](ui_events::pointer::PointerEvent)s,
/// [`TextEvent`]s and [`AccessEvent`]s, [`Update`] events
/// are generated by Masonry, and may occur at different times during a given pass of
/// the event loop.
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub enum Update {
    /// Sent to a `Widget` when it is added to the widget tree. This should be
    /// the first message that each widget receives.
    ///
    /// Widgets should handle this event in order to do any initial setup that cannot
    /// be done when constructing the widget.
    WidgetAdded,

    /// Called when the [disabled] state of the widget is changed.
    ///
    /// See also [`is_disabled`] and [`set_disabled`].
    ///
    /// [disabled]: crate::doc::masonry_concepts#disabled
    /// [`is_disabled`]: crate::core::EventCtx::is_disabled
    /// [`set_disabled`]: crate::core::EventCtx::set_disabled
    DisabledChanged(bool),

    /// Called when the [stashed] state of the widget is changed.
    ///
    /// See also [`is_stashed`] and [`set_stashed`].
    ///
    /// [stashed]: crate::doc::masonry_concepts#stashed
    /// [`is_stashed`]: crate::core::EventCtx::is_stashed
    /// [`set_stashed`]: crate::core::EventCtx::set_stashed
    StashedChanged(bool),

    /// Called when a descendant widget requests to be scrolled to.
    ///
    /// The included [`Rect`] is in the receiving widget's content-box coordinate space.
    ///
    /// See also [`EventCtx::request_scroll_to_this`] and [`EventCtx::request_scroll_to`].
    ///
    /// [`EventCtx::request_scroll_to_this`]: crate::core::EventCtx::request_scroll_to_this
    /// [`EventCtx::request_scroll_to`]: crate::core::EventCtx::request_scroll_to
    RequestPanToChild(Rect),

    /// Called when the [hovered] status of the current widget changes.
    ///
    /// [hovered]: crate::doc::masonry_concepts#widget-status
    HoveredChanged(bool),

    /// Called when the [hovered] status of the current widget or a descendant changes.
    ///
    /// This is sent before [`Update::HoveredChanged`].
    ///
    /// [hovered]: crate::doc::masonry_concepts#widget-status
    ChildHoveredChanged(bool),

    /// Called when the [active] status of the current widget changes.
    ///
    /// [active]: crate::doc::masonry_concepts#widget-status
    ActiveChanged(bool),

    /// Called when the [active] status of the current widget or a descendant changes.
    ///
    /// This is sent before [`Update::ActiveChanged`].
    ///
    /// [active]: crate::doc::masonry_concepts#widget-status
    ChildActiveChanged(bool),

    /// Called when the [focused] status of the current widget changes.
    ///
    /// [focused]: crate::doc::masonry_concepts#text-focus
    FocusChanged(bool),

    /// Called when the [focused] status of the current widget or a descendant changes.
    ///
    /// This is sent before [`Update::FocusChanged`].
    ///
    /// [focused]: crate::doc::masonry_concepts#text-focus
    ChildFocusChanged(bool),

    /// Called when available fonts have changed.
    ///
    /// Widgets that directly use fonts should recompute their font selection.
    FontsChanged,
}

/// An enum for specifying whether an event was handled.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum Handled {
    /// An event was already handled, and shouldn't be propagated to other event handlers.
    Yes,
    /// An event has not yet been handled.
    No,
}

// --- MARK: IMPLS

impl TextEvent {
    /// Constructor for keyboard events with [`KeyState::Down`].
    ///
    /// The key code will be marked as [`Code::Unidentified`].
    pub fn key_down(key: Key) -> Self {
        Self::Keyboard(KeyboardEvent {
            state: KeyState::Down,
            key,
            code: Code::Unidentified,
            ..Default::default()
        })
    }

    /// Constructor for keyboard events with [`KeyState::Up`].
    ///
    /// The key code will be marked as [`Code::Unidentified`].
    pub fn key_up(key: Key) -> Self {
        Self::Keyboard(KeyboardEvent {
            state: KeyState::Up,
            key,
            code: Code::Unidentified,
            ..Default::default()
        })
    }

    /// Constructor for [`TextInputEvent::CompositionUpdate`] events.
    ///
    /// This is mostly useful for testing.
    pub fn preedit(text: String) -> Self {
        Self::TextInput(TextInputEvent::CompositionUpdate(CompositionState::new(
            text,
        )))
    }

    /// Constructor for [`TextInputEvent::CompositionUpdate`] events.
    ///
    /// This is mostly useful for testing.
    ///
    /// **selected** is the part of the preedit text that should be selected.
    ///
    /// # Panics
    ///
    /// If **selected** isn't a substring of **text**.
    pub fn preedit_with_cursor(text: String, selected: String) -> Self {
        let Some(offset) = text.find(&selected) else {
            panic!("Error building Preedit event: '{selected}' not found in '{text}'");
        };
        let start = u32::try_from(offset).expect("selected start exceeds u32");
        let end = u32::try_from(offset + selected.len()).expect("selected end exceeds u32");
        Self::TextInput(TextInputEvent::CompositionUpdate(
            CompositionState::new(text).with_selection(TextRange::new(start, end)),
        ))
    }

    /// Short name of the event, for debug logging.
    pub fn short_name(&self) -> &'static str {
        match self {
            Self::Keyboard(KeyboardEvent { repeat: true, .. }) => "Keyboard(repeat)",
            Self::Keyboard(..) => "Keyboard",
            Self::TextInput(TextInputEvent::Insert(_)) => "TextInput::Insert",
            Self::TextInput(TextInputEvent::DeleteBackward) => "TextInput::DeleteBackward",
            Self::TextInput(TextInputEvent::DeleteForward) => "TextInput::DeleteForward",
            Self::TextInput(TextInputEvent::DeleteSurrounding(_)) => "TextInput::DeleteSurrounding",
            Self::TextInput(TextInputEvent::SetSelection(_)) => "TextInput::SetSelection",
            Self::TextInput(TextInputEvent::SetComposingRegion(_)) => {
                "TextInput::SetComposingRegion"
            }
            Self::TextInput(TextInputEvent::CompositionUpdate(state)) if state.text.is_empty() => {
                "TextInput::CompositionUpdate(\"\")"
            }
            Self::TextInput(TextInputEvent::CompositionUpdate(_)) => {
                "TextInput::CompositionUpdate(\"...\")"
            }
            Self::TextInput(TextInputEvent::CompositionEnd) => "TextInput::CompositionEnd",
            Self::TextInput(TextInputEvent::Action(_)) => "TextInput::Action",
            Self::WindowFocusChange(_) => "WindowFocusChange",
            Self::ClipboardPaste(_) => "ClipboardPaste",
        }
    }
}

impl AccessEvent {
    /// Short name of the event, for debug logging.
    ///
    /// Returns the enum variant name.
    pub fn short_name(&self) -> &'static str {
        match self.action {
            accesskit::Action::Click => "Click",
            accesskit::Action::Focus => "Focus",
            accesskit::Action::Blur => "Blur",
            accesskit::Action::Collapse => "Collapse",
            accesskit::Action::Expand => "Expand",
            accesskit::Action::CustomAction => "CustomAction",
            accesskit::Action::Decrement => "Decrement",
            accesskit::Action::Increment => "Increment",
            accesskit::Action::HideTooltip => "HideTooltip",
            accesskit::Action::ShowTooltip => "ShowTooltip",
            accesskit::Action::ReplaceSelectedText => "ReplaceSelectedText",
            accesskit::Action::ScrollDown => "ScrollDown",
            accesskit::Action::ScrollLeft => "ScrollLeft",
            accesskit::Action::ScrollRight => "ScrollRight",
            accesskit::Action::ScrollUp => "ScrollUp",
            accesskit::Action::ScrollIntoView => "ScrollIntoView",
            accesskit::Action::ScrollToPoint => "ScrollToPoint",
            accesskit::Action::SetScrollOffset => "SetScrollOffset",
            accesskit::Action::SetTextSelection => "SetTextSelection",
            accesskit::Action::SetSequentialFocusNavigationStartingPoint => {
                "SetSequentialFocusNavigationStartingPoint"
            }
            accesskit::Action::SetValue => "SetValue",
            accesskit::Action::ShowContextMenu => "ShowContextMenu",
        }
    }
}

impl Update {
    /// Short name of the event, for debug logging.
    ///
    /// Returns the enum variant name.
    pub fn short_name(&self) -> &str {
        match self {
            Self::WidgetAdded => "WidgetAdded",
            Self::DisabledChanged(false) => "DisabledChanged(false)",
            Self::StashedChanged(false) => "StashedChanged(false)",
            Self::HoveredChanged(false) => "HoveredChanged(false)",
            Self::ChildHoveredChanged(false) => "ChildHoveredChanged(false)",
            Self::ActiveChanged(false) => "ActiveChanged(false)",
            Self::ChildActiveChanged(false) => "ChildActiveChanged(false)",
            Self::FocusChanged(false) => "FocusChanged(false)",
            Self::ChildFocusChanged(false) => "ChildFocusChanged(false)",
            Self::DisabledChanged(true) => "DisabledChanged(true)",
            Self::StashedChanged(true) => "StashedChanged(true)",
            Self::HoveredChanged(true) => "HoveredChanged(true)",
            Self::ChildHoveredChanged(true) => "ChildHoveredChanged(true)",
            Self::ActiveChanged(true) => "ActiveChanged(true)",
            Self::ChildActiveChanged(true) => "ChildActiveChanged(true)",
            Self::FocusChanged(true) => "FocusChanged(true)",
            Self::ChildFocusChanged(true) => "ChildFocusChanged(true)",
            Self::RequestPanToChild(_) => "RequestPanToChild(_)",
            Self::FontsChanged => "FontsChanged",
        }
    }
}

impl Handled {
    /// Has the event been handled yet?
    pub fn is_handled(self) -> bool {
        self == Self::Yes
    }
}

impl From<bool> for Handled {
    /// Returns `Handled::Yes` if `handled` is true, and `Handled::No` otherwise.
    fn from(handled: bool) -> Self {
        if handled { Self::Yes } else { Self::No }
    }
}

/// Defines the orientation that a window resize will be performed.
///
/// Mirrors [`winit::window::ResizeDirection`](https://docs.rs/winit/latest/x86_64-unknown-linux-gnu/winit/window/enum.ResizeDirection.html).
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
#[expect(missing_docs, reason = "Copied from winit")]
pub enum ResizeDirection {
    East,
    North,
    NorthEast,
    NorthWest,
    South,
    SouthEast,
    SouthWest,
    West,
}
