[package]
name = "todomvc"
version = "0.1.0"
publish = false
license.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
console_error_panic_hook = "0.1.7"
serde = { version = "1.0.170", features = ["derive"] }
serde_json = "1.0.100"
tracing = "0.1.37"
tracing-wasm = "0.2.1"
wasm-bindgen = "0.2.87"
web-sys = { version = "0.3.64", features = ["Storage", "Window"] }
xilem_web = { path = "../.." }
