// Copyright 2025 the Xilem Authors
// SPDX-License-Identifier: Apache-2.0

//! Stress test for the build speed of Xilem components.

use std::hint::black_box;

use xilem::WidgetView;
use xilem::core::ViewArgument;
use xilem::view::{
    checkbox, flex_row, label, portal, progress_bar, prose, sized_box, slider, spinner, split,
    text_button, text_input,
};
use xilem_core::MessageResult;
use xilem_core::map_message;

fn widgets<State: ViewArgument + Send + Sync, const N: usize>()
-> impl WidgetView<State> + use<State, N> {
    map_message(
        flex_row((
            text_button("button", |_| unimplemented!()),
            checkbox("checkbox", true, |_, _| unimplemented!()),
            label("label"),
            portal(progress_bar(Some(0.))),
            prose("prose"),
            sized_box(slider(0., 0., 0., |_, _| unimplemented!())),
            spinner(),
            split(
                text_input("input".into(), |_, _| unimplemented!()),
                text_input("input".into(), |_, _| unimplemented!()),
            ),
        )),
        |_, _message: MessageResult<[u32; N]>| MessageResult::Nop,
    )
}

#[cfg(feature = "compile-stress-test")]
fn mega_component() -> impl WidgetView<()> + use<> {
    flex_row([
        // Because the line!() macro gives a different number every line,
        // each line generates a new generic instantiation of widgets().
        // You can add or remove copies to adjust the build time of this file.
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
        widgets::<(), { line!() as usize }>().boxed(),
    ])
}

#[cfg(not(feature = "compile-stress-test"))]
fn mega_component() -> impl WidgetView<()> + use<> {
    flex_row(
        // We use only one to check it compiles
        widgets::<(), { line!() as usize }>().boxed(),
    )
}

#[test]
fn test() {
    black_box(mega_component().boxed());
}
